### ISSUE TITLE
Won't work in Linux as it is. Make it generic. 

### ISSUE THREAD

**Issue by kdpisda** [Sumit2514/AI_CHAMP#1]
https://github.com/Sumit2514/AI_CHAMP/blob/2e29a0f5cbbd8ce3cbb3811eb184114315d84451/Task%202/Task_2.py#L29

**Comment by Sumit2514** [comment]
SIr I have made the correction in the code 

text=slate.PDF(open('Profile ('+str(i)+').pdf', 'rb')).text()
arr.to_csv (r'Profile_text.csv' ,index = False, header=True)


> https://github.com/Sumit2514/AI_CHAMP/blob/2e29a0f5cbbd8ce3cbb3811eb184114315d84451/Task%202/Task_2.py#L29
