### ISSUE TITLE
Won't work in linux, make it generic

### ISSUE THREAD

**Issue by kdpisda** [Sumit2514/AI_CHAMP#2]
https://github.com/Sumit2514/AI_CHAMP/blob/2e29a0f5cbbd8ce3cbb3811eb184114315d84451/Task%203/Task_3.py#L93

**Comment by Sumit2514** [comment]
Sir I have made the correction in the code.

data.to_csv (r'Profile_keyword.csv' ,index = False, header=True)



> https://github.com/Sumit2514/AI_CHAMP/blob/2e29a0f5cbbd8ce3cbb3811eb184114315d84451/Task%203/Task_3.py#L93
